<template>
  <section>
        

        <div>
                <div class="footer bg-primary text-black font-medium p-6">
                    <div class="container mx-auto px-16">
                        <div class="flex items-center justify-between text-white">
                            <div class="flex items-center">
                                <p>&copy; PPS 2019</p>
                            </div>
                            <div class="flex">
                                <ul class="flex justify-end">
                                    <li class="pr-3 pl-3">Site Map</li>
                                    <li class="pr-3 pl-3">Legal & Cookies</li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
         </div>

    </section>
    
</template>