<template>
  <section>
        <div class="footer text-black font-medium p-6">
            <div class="container mx-auto px-16">
                <div class="flex flex-row text-white">
                    <div class=" bg-secondary p-12 w-1/4">
                        <div>
                            <h3 class="text-2xl pb-10">Support Services</h3>
                            <p>From advice and training on our products to
                                maintenance and repairs, we can help.</p>
                        </div>
                    </div>
                    <div class=" bg-optional p-12 w-1/4">
                        <div>
                            <h3 class="text-2xl pb-10">Technical Hub</h3>
                            <p>Detailed technical specifications on our products
                                allow you to make informed choices. </p>
                        </div>
                    </div>
                    <div class=" bg-primary p-12 flex-1">
                        <div>
                            <h3 class="text-2xl pb-4">Contact Details</h3>

                            <p class=" pb-10">Professional Protection Systems
                                Ltd<br>
                                t +44 (0)1908 272240<br>
                                f +44 (0)1908 371605<br>
                                e sales@ppsgb.com
                            </p>

                            <p class=" pb-10">Protection House,<br>
                                Sherbourne Drive,<br>
                                Tilbrook,<br>
                                Milton Keynes,<br>
                                MK7 8HX <br>
                                Registered in the United Kingdom<br>
                                Registered name: Professional Protection
                                Systems<br>
                                Registered number: 4494024<br>
                            </p>

                            <p>Trading name: PPS</p>




                        </div>
                </div>
            </div>
        </div>
        </div>

        <div>
                <div class="footer bg-primary text-black font-medium p-6">
                    <div class="container mx-auto px-16">
                        <div class="flex items-center justify-between text-white">
                            <div class="flex items-center">
                                <p>&copy; PPS 2019</p>
                            </div>
                            <div class="flex">
                                <ul class="flex justify-end">
                                    <li class="pr-3 pl-3">Site Map</li>
                                    <li class="pr-3 pl-3">Legal & Cookies</li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
         </div>

    </section>
    
</template>